files:
  include: 'assets/styles/**/*.s+(a|c)ss'

rules:
  class-name-format: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero: 0
  nesting-depth: 0
  no-color-literals: 0
  no-important: 0
  property-sort-order: 0
  single-line-per-selector: 0
  variable-name-format: 0
